// GENERATED by tools/gen-protocol.mjs - DO NOT EDIT.
// Source: github.com/ZeroK-RTS/Zero-K-Infrastructure @ 48f6f09bc1d0266f204026580671ce867f75d6bd
// Regenerate: node tools/gen-protocol.mjs

export enum Origin {
  Server = 1,
  Client = 2,
}

export enum Login_ClientTypes {
  ZeroKLobby = 1,
  Linux = 2,
}

export enum RegisterResponse_Code {
  Ok = 0,
  AlreadyConnected = 1,
  NameAlreadyTaken = 2,
  InvalidPassword = 3,
  Banned = 4,
  NameHasInvalidCharacters = 5,
  InvalidSteamToken = 6,
  SteamAlreadyRegistered = 7,
  MissingBothPasswordAndToken = 8,
  BannedTooManyAttempts = 9,
  AlreadyRegisteredWithThisSteamToken = 10,
  AlreadyRegisteredWithThisPassword = 11,
}

/** Display labels from the upstream [Description] attributes. */
export const RegisterResponse_CodeLabel: Record<RegisterResponse_Code, string> = {
  [RegisterResponse_Code.Ok]: "Ok",
  [RegisterResponse_Code.AlreadyConnected]: "already connected",
  [RegisterResponse_Code.NameAlreadyTaken]: "name already exists",
  [RegisterResponse_Code.InvalidPassword]: "invalid password",
  [RegisterResponse_Code.Banned]: "banned",
  [RegisterResponse_Code.NameHasInvalidCharacters]: "invalid name characters",
  [RegisterResponse_Code.InvalidSteamToken]: "invalid steam token, are you in offline mode?",
  [RegisterResponse_Code.SteamAlreadyRegistered]: "steam already registered",
  [RegisterResponse_Code.MissingBothPasswordAndToken]: "missing both password and token",
  [RegisterResponse_Code.BannedTooManyAttempts]: "banned too many connection attempts",
  [RegisterResponse_Code.AlreadyRegisteredWithThisSteamToken]: "already linked steam, connecting",
  [RegisterResponse_Code.AlreadyRegisteredWithThisPassword]: "already registered, use login using password",
};

export enum LoginResponse_Code {
  Ok = 0,
  InvalidName = 2,
  InvalidPassword = 3,
  Banned = 4,
  InvalidSteamToken = 5,
  BannedTooManyConnectionAttempts = 6,
  SteamNotLinkedAndLoginMissing = 7,
  SteamLinkedToDifferentAccount = 8,
  ServerFull = 9,
  InvalidRsaSignature = 10,
  RsaSignatureCouldNotBeVerified = 11,
}

/** Display labels from the upstream [Description] attributes. */
export const LoginResponse_CodeLabel: Record<LoginResponse_Code, string> = {
  [LoginResponse_Code.Ok]: "Ok",
  [LoginResponse_Code.InvalidName]: "invalid name",
  [LoginResponse_Code.InvalidPassword]: "invalid password",
  [LoginResponse_Code.Banned]: "banned",
  [LoginResponse_Code.InvalidSteamToken]: "invalid steam token, are you in offline mode?",
  [LoginResponse_Code.BannedTooManyConnectionAttempts]: "banned, too many connection attempts",
  [LoginResponse_Code.SteamNotLinkedAndLoginMissing]: "your steam account is not linked yet, send ZK login or register",
  [LoginResponse_Code.SteamLinkedToDifferentAccount]: "your steam account is already linked to a different account",
  [LoginResponse_Code.ServerFull]: "sorry, the server is full, please retry later",
  [LoginResponse_Code.InvalidRsaSignature]: "invalid RSA signature",
  [LoginResponse_Code.RsaSignatureCouldNotBeVerified]: "RSA signature could not be verified (pub key not known)",
};

export enum SayPlace {
  Channel = 0,
  Battle = 1,
  User = 2,
  BattlePrivate = 3,
  Game = 4,
  MessageBox = 5,
}

export enum SaySource {
  Discord = 0,
  Spring = 1,
  Zk = 2,
  DiscordSpring = 3,
}

export enum PwMatchCommand_ModeType {
  Clear = 0,
  Attack = 1,
  Defend = 2,
}

export enum AutohostMode {
  GameChickens = 5,
  Teams = 6,
  Game1v1 = 3,
  GameFFA = 4,
  None = 0,
  Planetwars = 2,
}

/** Display labels from the upstream [Description] attributes. */
export const AutohostModeLabel: Record<AutohostMode, string> = {
  [AutohostMode.GameChickens]: "Cooperative",
  [AutohostMode.Teams]: "Teams",
  [AutohostMode.Game1v1]: "1v1",
  [AutohostMode.GameFFA]: "FFA",
  [AutohostMode.None]: "Custom",
  [AutohostMode.Planetwars]: "PlanetWars",
};

export enum Relation {
  None = 0,
  Friend = 1,
  Ignore = 2,
}

export enum SyncStatuses {
  Unknown = 0,
  Synced = 1,
  Unsynced = 2,
}

