// GENERATED by tools/gen-protocol.mjs - DO NOT EDIT.
// Source: github.com/ZeroK-RTS/Zero-K-Infrastructure @ 48f6f09bc1d0266f204026580671ce867f75d6bd
// Regenerate: node tools/gen-protocol.mjs

import type * as T from "./types";

/** Every top-level protocol command, keyed by the name that precedes the JSON on the wire. */
export interface MessageMap {
  AreYouReady: T.AreYouReady;
  AreYouReadyResponse: T.AreYouReadyResponse;
  AreYouReadyResult: T.AreYouReadyResult;
  AreYouReadyUpdate: T.AreYouReadyUpdate;
  BattleAdded: T.BattleAdded;
  BattleDebriefing: T.BattleDebriefing;
  BattleHeader: T.BattleHeader;
  BattlePoll: T.BattlePoll;
  BattlePollOutcome: T.BattlePollOutcome;
  BattleRemoved: T.BattleRemoved;
  BattleUpdate: T.BattleUpdate;
  ChangeTopic: T.ChangeTopic;
  ChangeUserStatus: T.ChangeUserStatus;
  ChannelHeader: T.ChannelHeader;
  ChannelUserAdded: T.ChannelUserAdded;
  ChannelUserRemoved: T.ChannelUserRemoved;
  ConnectSpring: T.ConnectSpring;
  CustomGameModeResponse: T.CustomGameModeResponse;
  DefaultEngineChanged: T.DefaultEngineChanged;
  DefaultGameChanged: T.DefaultGameChanged;
  ForceJoinBattle: T.ForceJoinBattle;
  ForceJoinChannel: T.ForceJoinChannel;
  ForumList: T.ForumList;
  FriendEntry: T.FriendEntry;
  FriendList: T.FriendList;
  GetCustomGameMode: T.GetCustomGameMode;
  IgnoreList: T.IgnoreList;
  InviteToParty: T.InviteToParty;
  JoinBattle: T.JoinBattle;
  JoinBattleSuccess: T.JoinBattleSuccess;
  JoinChannel: T.JoinChannel;
  JoinChannelResponse: T.JoinChannelResponse;
  JoinFactionRequest: T.JoinFactionRequest;
  KickFromBattle: T.KickFromBattle;
  KickFromChannel: T.KickFromChannel;
  KickFromServer: T.KickFromServer;
  LadderList: T.LadderList;
  LeaveBattle: T.LeaveBattle;
  LeaveChannel: T.LeaveChannel;
  LeaveParty: T.LeaveParty;
  Login: T.Login;
  LoginResponse: T.LoginResponse;
  MatchMakerQueueRequest: T.MatchMakerQueueRequest;
  MatchMakerSetup: T.MatchMakerSetup;
  MatchMakerStatus: T.MatchMakerStatus;
  NewsList: T.NewsList;
  OnPartyInvite: T.OnPartyInvite;
  OnPartyStatus: T.OnPartyStatus;
  OpenBattle: T.OpenBattle;
  PartyInviteResponse: T.PartyInviteResponse;
  PwAttackCharges: T.PwAttackCharges;
  PwAttackingPlanet: T.PwAttackingPlanet;
  PwCancel: T.PwCancel;
  PwJoinPlanet: T.PwJoinPlanet;
  PwJoinPlanetSuccess: T.PwJoinPlanetSuccess;
  PwMatchCommand: T.PwMatchCommand;
  PwRequestJoinPlanet: T.PwRequestJoinPlanet;
  PwStatus: T.PwStatus;
  Register: T.Register;
  RegisterResponse: T.RegisterResponse;
  RejoinOption: T.RejoinOption;
  RemoveBot: T.RemoveBot;
  RequestConnectSpring: T.RequestConnectSpring;
  Say: T.Say;
  SetAccountRelation: T.SetAccountRelation;
  SetMapOptions: T.SetMapOptions;
  SetModOptions: T.SetModOptions;
  SiteToLobbyCommand: T.SiteToLobbyCommand;
  Topic: T.Topic;
  UpdateBotStatus: T.UpdateBotStatus;
  UpdateUserBattleStatus: T.UpdateUserBattleStatus;
  User: T.User;
  UserDisconnected: T.UserDisconnected;
  UserProfile: T.UserProfile;
  UserReport: T.UserReport;
  Welcome: T.Welcome;
}

export type CommandName = keyof MessageMap;

/** Discriminated union of every decoded message. */
export type Message = { [K in CommandName]: { cmd: K; data: MessageMap[K] } }[CommandName];

export const COMMAND_NAMES = [
  "AreYouReady",
  "AreYouReadyResponse",
  "AreYouReadyResult",
  "AreYouReadyUpdate",
  "BattleAdded",
  "BattleDebriefing",
  "BattleHeader",
  "BattlePoll",
  "BattlePollOutcome",
  "BattleRemoved",
  "BattleUpdate",
  "ChangeTopic",
  "ChangeUserStatus",
  "ChannelHeader",
  "ChannelUserAdded",
  "ChannelUserRemoved",
  "ConnectSpring",
  "CustomGameModeResponse",
  "DefaultEngineChanged",
  "DefaultGameChanged",
  "ForceJoinBattle",
  "ForceJoinChannel",
  "ForumList",
  "FriendEntry",
  "FriendList",
  "GetCustomGameMode",
  "IgnoreList",
  "InviteToParty",
  "JoinBattle",
  "JoinBattleSuccess",
  "JoinChannel",
  "JoinChannelResponse",
  "JoinFactionRequest",
  "KickFromBattle",
  "KickFromChannel",
  "KickFromServer",
  "LadderList",
  "LeaveBattle",
  "LeaveChannel",
  "LeaveParty",
  "Login",
  "LoginResponse",
  "MatchMakerQueueRequest",
  "MatchMakerSetup",
  "MatchMakerStatus",
  "NewsList",
  "OnPartyInvite",
  "OnPartyStatus",
  "OpenBattle",
  "PartyInviteResponse",
  "PwAttackCharges",
  "PwAttackingPlanet",
  "PwCancel",
  "PwJoinPlanet",
  "PwJoinPlanetSuccess",
  "PwMatchCommand",
  "PwRequestJoinPlanet",
  "PwStatus",
  "Register",
  "RegisterResponse",
  "RejoinOption",
  "RemoveBot",
  "RequestConnectSpring",
  "Say",
  "SetAccountRelation",
  "SetMapOptions",
  "SetModOptions",
  "SiteToLobbyCommand",
  "Topic",
  "UpdateBotStatus",
  "UpdateUserBattleStatus",
  "User",
  "UserDisconnected",
  "UserProfile",
  "UserReport",
  "Welcome"
] as const;

const COMMAND_SET: ReadonlySet<string> = new Set(COMMAND_NAMES);

export function isCommandName(s: string): s is CommandName {
  return COMMAND_SET.has(s);
}
