// GENERATED by tools/gen-settings.mjs - DO NOT EDIT.
// Source: github.com/ZeroK-RTS/Chobby @ 8fed2a62a8e1d4f325aea013743ab82314c9396e
//         LuaMenu/configs/gameConfig/zk/settingsMenu.lua
// Regenerate: node tools/gen-settings.mjs

/** A value a setting can hold: an option name, or a number for sliders. */
export type SettingValue = string | number;

/** A bound upstream computes from the screen rather than writing down. */
export interface SettingRef { ref: string; }

export interface SettingOption {
  name: string;
  /** springsettings.cfg keys this option writes, verbatim from upstream. */
  apply?: Record<string, SettingValue>;
  /** Upstream applies this one with Lua; see src/net/gameSettings.ts. */
  computed?: string;
  /** ShaderDetail alone selects a template file instead of writing keys. */
  file?: string;
}

export interface Setting {
  name: string;
  humanName: string;
  kind: "options" | "number" | "unsupported";
  options?: SettingOption[];
  min?: number | SettingRef;
  max?: number | SettingRef;
  /** A percentage, so 100 means unscaled. */
  percent?: boolean;
  /** A number setting that writes exactly this key. */
  applyName?: string;
  computed?: string;
  /** Why an unsupported setting is not offered. */
  why?: string;
}

export interface SettingsPreset {
  name: string;
  /** The Game tab's default carries a bound upstream reads off the screen. */
  values: Record<string, SettingValue | SettingRef>;
}
export interface SettingsTab {
  name: string;
  presets: SettingsPreset[];
  settings: Setting[];
}

export const SETTINGS_TABS: SettingsTab[] = [
  {
    "name": "Graphics",
    "presets": [
      {
        "name": "Compat.",
        "values": {
          "WaterType_2": "Basic",
          "WaterQuality": "Low",
          "Shadows": "None",
          "ShadowMapSize": "1024",
          "ParticleLimit": "2000",
          "TerrainDetail": "Minimal",
          "SoftParticles": "Compatibility",
          "VegetationDetail": "Minimal",
          "FeatureFade": "On",
          "CompatibilityMode": "On",
          "AtiIntelCompatibility_2": "Automatic",
          "AntiAliasing": "Off",
          "VSync": "Off",
          "ShaderDetail": "Minimal",
          "LupsAirJet": "Off",
          "LupsRibbon": "Off",
          "LupsNanoParticles": "Beam",
          "LupsShieldShader": "Off",
          "LupsWaterSettings": "Off",
          "FancySky": "Off",
          "UseNewChili": "Off"
        }
      },
      {
        "name": "Lowest",
        "values": {
          "WaterType_2": "Bumpmapped",
          "WaterQuality": "Low",
          "Shadows": "None",
          "ShadowMapSize": "1024",
          "ParticleLimit": "6000",
          "TerrainDetail": "Low",
          "SoftParticles": "Enabled",
          "VegetationDetail": "Low",
          "FeatureFade": "On",
          "CompatibilityMode": "Off",
          "AtiIntelCompatibility_2": "Automatic",
          "AntiAliasing": "Low",
          "VSync": "Off",
          "ShaderDetail": "Minimal",
          "LupsAirJet": "Off",
          "LupsRibbon": "Off",
          "LupsNanoParticles": "Beam",
          "LupsShieldShader": "Off",
          "LupsWaterSettings": "Off",
          "FancySky": "Off",
          "UseNewChili": "Off"
        }
      },
      {
        "name": "Low",
        "values": {
          "WaterType_2": "Bumpmapped",
          "WaterQuality": "Low",
          "Shadows": "Units Only",
          "ShadowMapSize": "2048",
          "ParticleLimit": "12000",
          "TerrainDetail": "Low",
          "SoftParticles": "Enabled",
          "VegetationDetail": "Low",
          "FeatureFade": "On",
          "CompatibilityMode": "Off",
          "AtiIntelCompatibility_2": "Automatic",
          "AntiAliasing": "Low",
          "VSync": "Off",
          "ShaderDetail": "Low",
          "LupsAirJet": "Off",
          "LupsRibbon": "On",
          "LupsNanoParticles": "Beam",
          "LupsShieldShader": "Default",
          "LupsWaterSettings": "Off",
          "FancySky": "Off",
          "UseNewChili": "Off"
        }
      },
      {
        "name": "Medium",
        "values": {
          "WaterType_2": "Bumpmapped",
          "WaterQuality": "Medium",
          "Shadows": "Units and Terrain",
          "ShadowMapSize": "2048",
          "ParticleLimit": "15000",
          "TerrainDetail": "Medium",
          "SoftParticles": "Enabled",
          "VegetationDetail": "Medium",
          "FeatureFade": "On",
          "CompatibilityMode": "Off",
          "AtiIntelCompatibility_2": "Automatic",
          "AntiAliasing": "Low",
          "VSync": "Off",
          "ShaderDetail": "Medium",
          "LupsAirJet": "On",
          "LupsRibbon": "On",
          "LupsNanoParticles": "Cloud",
          "LupsShieldShader": "Default",
          "LupsWaterSettings": "Off",
          "FancySky": "Off",
          "UseNewChili": "Off"
        }
      },
      {
        "name": "High",
        "values": {
          "WaterType_2": "Bumpmapped",
          "WaterQuality": "High",
          "Shadows": "Units and Terrain",
          "ShadowMapSize": "8192",
          "ParticleLimit": "25000",
          "TerrainDetail": "High",
          "SoftParticles": "Enabled",
          "VegetationDetail": "High",
          "FeatureFade": "On",
          "CompatibilityMode": "Off",
          "AtiIntelCompatibility_2": "Automatic",
          "AntiAliasing": "High",
          "VSync": "Off",
          "ShaderDetail": "High",
          "LupsAirJet": "On",
          "LupsRibbon": "On",
          "LupsNanoParticles": "Cloud",
          "LupsShieldShader": "Default",
          "LupsWaterSettings": "Off",
          "FancySky": "Off",
          "UseNewChili": "Off"
        }
      }
    ],
    "settings": [
      {
        "name": "DisplayMode",
        "humanName": "Ingame Display Mode",
        "kind": "unsupported",
        "why": "Shiro manages its own window"
      },
      {
        "name": "LobbyDisplayMode",
        "humanName": "Menu Display Mode",
        "kind": "unsupported",
        "why": "Shiro manages its own window"
      },
      {
        "name": "ActiveGraphicsLabel",
        "humanName": "Graphics Driver Selected",
        "kind": "unsupported",
        "why": "a text label, not a setting"
      },
      {
        "name": "AntiAliasing",
        "humanName": "Anti Aliasing",
        "kind": "options",
        "options": [
          {
            "name": "Off",
            "apply": {
              "MSAALevel": 1,
              "FSAA": 0,
              "SmoothLines": 0,
              "SmoothPoints": 0
            }
          },
          {
            "name": "Low",
            "apply": {
              "MSAALevel": 4,
              "FSAA": 1,
              "SmoothLines": 1,
              "SmoothPoints": 1
            }
          },
          {
            "name": "High",
            "apply": {
              "MSAALevel": 8,
              "FSAA": 1,
              "SmoothLines": 3,
              "SmoothPoints": 3
            }
          }
        ]
      },
      {
        "name": "LupsAirJet",
        "humanName": "Aircraft Jets",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "computed": "LupsAirJet"
          },
          {
            "name": "Off",
            "computed": "LupsAirJet"
          }
        ]
      },
      {
        "name": "LupsRibbon",
        "humanName": "Aircraft Wing Trails",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "computed": "LupsRibbon"
          },
          {
            "name": "Off",
            "computed": "LupsRibbon"
          }
        ]
      },
      {
        "name": "CompatibilityMode",
        "humanName": "Compatibility Mode",
        "kind": "options",
        "options": [
          {
            "name": "Off",
            "apply": {
              "AllowDeferredModelRendering": 1,
              "AllowDeferredMapRendering": 1,
              "LoadingMT": 0,
              "AdvUnitShading": 1,
              "AdvMapShading": 1,
              "LuaShaders": 1,
              "CubeTexSizeReflection": 1024,
              "ForceDisableShaders": 0,
              "UsePBO": 1,
              "3DTrees": 1,
              "MaxDynamicMapLights": 1,
              "MaxDynamicModelLights": 1,
              "ROAM": 1
            }
          },
          {
            "name": "On",
            "apply": {
              "AllowDeferredModelRendering": 1,
              "AllowDeferredMapRendering": 1,
              "LoadingMT": 0,
              "AdvUnitShading": 1,
              "AdvMapShading": 1,
              "LuaShaders": 1,
              "CubeTexSizeReflection": 1024,
              "ForceDisableShaders": 0,
              "UsePBO": 0,
              "3DTrees": 0,
              "MaxDynamicMapLights": 0,
              "MaxDynamicModelLights": 0,
              "ROAM": 1
            }
          },
          {
            "name": "Extreme",
            "apply": {
              "AllowDeferredModelRendering": 0,
              "AllowDeferredMapRendering": 0,
              "LoadingMT": 0,
              "AdvUnitShading": 0,
              "AdvMapShading": 0,
              "LuaShaders": 0,
              "CubeTexSizeReflection": 1,
              "ForceDisableShaders": 1,
              "UsePBO": 0,
              "3DTrees": 0,
              "MaxDynamicMapLights": 0,
              "MaxDynamicModelLights": 0,
              "ROAM": 1
            }
          }
        ]
      },
      {
        "name": "LupsNanoParticles",
        "humanName": "Construction Effect",
        "kind": "options",
        "options": [
          {
            "name": "Cloud",
            "computed": "LupsNanoParticles"
          },
          {
            "name": "Beam",
            "computed": "LupsNanoParticles"
          }
        ]
      },
      {
        "name": "UseNewChili",
        "humanName": "Experimental Interface Renderer",
        "kind": "options",
        "options": [
          {
            "name": "Off",
            "apply": {
              "ZKUseNewChiliRTT": 0
            }
          },
          {
            "name": "On",
            "apply": {
              "ZKUseNewChiliRTT": 1
            }
          }
        ]
      },
      {
        "name": "FancySky",
        "humanName": "Fancy Sky",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "apply": {
              "DynamicSky": 1,
              "AdvSky": 1
            }
          },
          {
            "name": "Off",
            "apply": {
              "DynamicSky": 0,
              "AdvSky": 0
            }
          }
        ]
      },
      {
        "name": "VSync",
        "humanName": "Frame Rate Limit (vsync)",
        "kind": "options",
        "options": [
          {
            "name": "Standard",
            "apply": {
              "VSync": 1
            }
          },
          {
            "name": "Adaptive",
            "apply": {
              "VSync": -1
            }
          },
          {
            "name": "Off",
            "apply": {
              "VSync": 0
            }
          }
        ]
      },
      {
        "name": "ParticleLimit",
        "humanName": "Particle Limit",
        "kind": "options",
        "options": [
          {
            "name": "2000",
            "apply": {
              "MaxParticles": 2000
            }
          },
          {
            "name": "4000",
            "apply": {
              "MaxParticles": 4000
            }
          },
          {
            "name": "6000",
            "apply": {
              "MaxParticles": 6000
            }
          },
          {
            "name": "9000",
            "apply": {
              "MaxParticles": 9000
            }
          },
          {
            "name": "12000",
            "apply": {
              "MaxParticles": 12000
            }
          },
          {
            "name": "15000",
            "apply": {
              "MaxParticles": 15000
            }
          },
          {
            "name": "20000",
            "apply": {
              "MaxParticles": 15000
            }
          },
          {
            "name": "25000",
            "apply": {
              "MaxParticles": 25000
            }
          },
          {
            "name": "35000",
            "apply": {
              "MaxParticles": 25000
            }
          },
          {
            "name": "50000",
            "apply": {
              "MaxParticles": 50000
            }
          }
        ]
      },
      {
        "name": "FeatureFade",
        "humanName": "Rock and Wreck Fade",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "apply": {
              "FeatureDrawDistance": 6000,
              "FeatureFadeDistance": 4500
            }
          },
          {
            "name": "Off",
            "apply": {
              "FeatureDrawDistance": 600000,
              "FeatureFadeDistance": 600000
            }
          }
        ]
      },
      {
        "name": "ShaderDetail",
        "humanName": "Shader Detail",
        "kind": "options",
        "options": [
          {
            "name": "Minimal",
            "file": "LuaMenu/configs/gameConfig/zk/lups/lups0.cfg",
            "computed": "ShaderDetail"
          },
          {
            "name": "Low",
            "file": "LuaMenu/configs/gameConfig/zk/lups/lups1.cfg",
            "computed": "ShaderDetail"
          },
          {
            "name": "Medium",
            "file": "LuaMenu/configs/gameConfig/zk/lups/lups2.cfg",
            "computed": "ShaderDetail"
          },
          {
            "name": "High",
            "file": "LuaMenu/configs/gameConfig/zk/lups/lups3.cfg",
            "computed": "ShaderDetail"
          },
          {
            "name": "Ultra",
            "file": "LuaMenu/configs/gameConfig/zk/lups/lups4.cfg",
            "computed": "ShaderDetail"
          }
        ]
      },
      {
        "name": "LupsWaterSettings",
        "humanName": "Shaders Affected by Water",
        "kind": "options",
        "options": [
          {
            "name": "Off",
            "computed": "LupsWaterSettings"
          },
          {
            "name": "Refraction",
            "computed": "LupsWaterSettings"
          },
          {
            "name": "Reflection",
            "computed": "LupsWaterSettings"
          },
          {
            "name": "Refract and Reflect",
            "computed": "LupsWaterSettings"
          }
        ]
      },
      {
        "name": "LupsShieldShader",
        "humanName": "Shield Effect Shader",
        "kind": "options",
        "options": [
          {
            "name": "Default",
            "computed": "LupsShieldShader"
          },
          {
            "name": "Simple",
            "computed": "LupsShieldShader"
          },
          {
            "name": "Off",
            "computed": "LupsShieldShader"
          }
        ]
      },
      {
        "name": "Shadows",
        "humanName": "Shadows",
        "kind": "options",
        "options": [
          {
            "name": "None",
            "apply": {
              "Shadows": 0
            }
          },
          {
            "name": "Units Only",
            "apply": {
              "Shadows": 2
            }
          },
          {
            "name": "Units and Terrain",
            "apply": {
              "Shadows": 1
            }
          }
        ]
      },
      {
        "name": "ShadowMapSize",
        "humanName": "Shadow Map Size",
        "kind": "options",
        "options": [
          {
            "name": "1024",
            "apply": {
              "ShadowMapSize": 1024
            }
          },
          {
            "name": "2048",
            "apply": {
              "ShadowMapSize": 2048
            }
          },
          {
            "name": "4096",
            "apply": {
              "ShadowMapSize": 4096
            }
          },
          {
            "name": "8192",
            "apply": {
              "ShadowMapSize": 8192
            }
          },
          {
            "name": "16384",
            "apply": {
              "ShadowMapSize": 16384
            }
          }
        ]
      },
      {
        "name": "SoftParticles",
        "humanName": "Soft Particles",
        "kind": "options",
        "options": [
          {
            "name": "Disabled",
            "apply": {
              "SoftParticles": 0
            }
          },
          {
            "name": "Compatibility",
            "apply": {
              "SoftParticles": 1
            }
          },
          {
            "name": "Enabled",
            "apply": {
              "SoftParticles": 2
            }
          }
        ]
      },
      {
        "name": "TerrainDetail",
        "humanName": "Terrain Detail",
        "kind": "options",
        "options": [
          {
            "name": "Minimal",
            "apply": {
              "GroundScarAlphaFade": 1,
              "GroundDecals": 0,
              "GroundDetail": 50
            }
          },
          {
            "name": "Low",
            "apply": {
              "GroundScarAlphaFade": 0,
              "GroundDecals": 1,
              "GroundDetail": 70
            }
          },
          {
            "name": "Medium",
            "apply": {
              "GroundScarAlphaFade": 1,
              "GroundDecals": 2,
              "GroundDetail": 90
            }
          },
          {
            "name": "High",
            "apply": {
              "GroundScarAlphaFade": 1,
              "GroundDecals": 5,
              "GroundDetail": 120
            }
          },
          {
            "name": "Ultra",
            "apply": {
              "GroundScarAlphaFade": 1,
              "GroundDecals": 10,
              "GroundDetail": 180
            }
          }
        ]
      },
      {
        "name": "UnitReflections",
        "humanName": "Unit Reflection Quality",
        "kind": "options",
        "options": [
          {
            "name": "Off",
            "apply": {
              "CubeTexSizeSpecular": 1
            }
          },
          {
            "name": "Low",
            "apply": {
              "CubeTexSizeSpecular": 64
            }
          },
          {
            "name": "Medium",
            "apply": {
              "CubeTexSizeSpecular": 128
            }
          },
          {
            "name": "High",
            "apply": {
              "CubeTexSizeSpecular": 256
            }
          },
          {
            "name": "Ultra",
            "apply": {
              "CubeTexSizeSpecular": 1024
            }
          }
        ]
      },
      {
        "name": "VegetationDetail",
        "humanName": "Vegetation Detail",
        "kind": "options",
        "options": [
          {
            "name": "Minimal",
            "apply": {
              "TreeRadius": 1000,
              "GrassDetail": 0
            }
          },
          {
            "name": "Low",
            "apply": {
              "TreeRadius": 1000,
              "GrassDetail": 0
            }
          },
          {
            "name": "Medium",
            "apply": {
              "TreeRadius": 1200,
              "GrassDetail": 0
            }
          },
          {
            "name": "High",
            "apply": {
              "TreeRadius": 1500,
              "GrassDetail": 0
            }
          },
          {
            "name": "Ultra",
            "apply": {
              "TreeRadius": 2500,
              "GrassDetail": 0
            }
          },
          {
            "name": "Ridiculous",
            "apply": {
              "TreeRadius": 2500,
              "GrassDetail": 0
            }
          }
        ]
      },
      {
        "name": "WaterType_2",
        "humanName": "Water Type",
        "kind": "options",
        "options": [
          {
            "name": "Basic",
            "apply": {
              "Water": 0
            }
          },
          {
            "name": "Reflective",
            "apply": {
              "Water": 1
            }
          },
          {
            "name": "Refractive",
            "apply": {
              "Water": 2
            }
          },
          {
            "name": "Bumpmapped",
            "apply": {
              "Water": 4
            }
          }
        ]
      },
      {
        "name": "WaterQuality",
        "humanName": "Water Quality",
        "kind": "options",
        "options": [
          {
            "name": "Low",
            "apply": {
              "BumpWaterAnisotropy": 0,
              "BumpWaterBlurReflection": 0,
              "BumpWaterReflection": 0,
              "BumpWaterRefraction": 0,
              "BumpWaterDepthBits": 16,
              "BumpWaterShoreWaves": 0,
              "BumpWaterTexSizeReflection": 64
            }
          },
          {
            "name": "Medium",
            "apply": {
              "BumpWaterAnisotropy": 0,
              "BumpWaterBlurReflection": 1,
              "BumpWaterReflection": 1,
              "BumpWaterRefraction": 1,
              "BumpWaterDepthBits": 24,
              "BumpWaterShoreWaves": 1,
              "BumpWaterTexSizeReflection": 128
            }
          },
          {
            "name": "High",
            "apply": {
              "BumpWaterAnisotropy": 2,
              "BumpWaterBlurReflection": 1,
              "BumpWaterReflection": 2,
              "BumpWaterRefraction": 1,
              "BumpWaterDepthBits": 32,
              "BumpWaterShoreWaves": 1,
              "BumpWaterTexSizeReflection": 256
            }
          },
          {
            "name": "Ultra",
            "apply": {
              "BumpWaterAnisotropy": 2,
              "BumpWaterBlurReflection": 1,
              "BumpWaterReflection": 2,
              "BumpWaterRefraction": 2,
              "BumpWaterDepthBits": 32,
              "BumpWaterShoreWaves": 1,
              "BumpWaterTexSizeReflection": 1024
            }
          }
        ]
      }
    ]
  },
  {
    "name": "Game",
    "presets": [
      {
        "name": "Default",
        "values": {
          "InterfaceScale": {
            "ref": "defaultUiScale"
          },
          "MouseZoomSpeed": 25,
          "InvertZoom": "Off",
          "HardwareCursor": "On",
          "EdgeScroll": "On",
          "CommandAlpha": 60,
          "QueueIconAlpha": 45,
          "MiddlePanSpeed": 15,
          "CameraPanSpeed": 50,
          "NetworkSettings": "Balanced",
          "SmoothBuffer": "Off"
        }
      }
    ],
    "settings": [
      {
        "name": "InterfaceScale",
        "humanName": "Game Interface Scale",
        "kind": "number",
        "min": {
          "ref": "minUiScale"
        },
        "max": {
          "ref": "maxUiScale"
        },
        "percent": true,
        "computed": "InterfaceScale"
      },
      {
        "name": "MouseZoomSpeed",
        "humanName": "Mouse Zoom Speed",
        "kind": "number",
        "min": 1,
        "max": 500,
        "applyName": "ScrollWheelSpeed",
        "computed": "MouseZoomSpeed"
      },
      {
        "name": "InvertZoom",
        "humanName": "Invert Zoom",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "computed": "InvertZoom"
          },
          {
            "name": "Off",
            "computed": "InvertZoom"
          }
        ]
      },
      {
        "name": "HardwareCursor",
        "humanName": "Hardware Cursor",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "apply": {
              "HardwareCursor": 1
            }
          },
          {
            "name": "Off",
            "apply": {
              "HardwareCursor": 0
            }
          }
        ]
      },
      {
        "name": "TextToSpeech",
        "humanName": "Text To Speech",
        "kind": "unsupported",
        "why": "reads out lobby chat in Chobby; Shiro has no equivalent"
      },
      {
        "name": "EdgeScroll",
        "humanName": "Screen Edge Scroll",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "apply": {
              "FullscreenEdgeMove": 1,
              "WindowedEdgeMove": 1
            }
          },
          {
            "name": "Off",
            "apply": {
              "FullscreenEdgeMove": 0,
              "WindowedEdgeMove": 0
            }
          }
        ]
      },
      {
        "name": "CommandAlpha",
        "humanName": "Command Line Alpha (%)",
        "kind": "number",
        "min": 10,
        "max": 100,
        "computed": "CommandAlpha"
      },
      {
        "name": "QueueIconAlpha",
        "humanName": "Command Icon Alpha (%)",
        "kind": "number",
        "min": 10,
        "max": 100,
        "computed": "QueueIconAlpha"
      },
      {
        "name": "MiddlePanSpeed",
        "humanName": "Middle Click Pan Speed",
        "kind": "number",
        "min": 0,
        "max": 1000,
        "computed": "MiddlePanSpeed"
      },
      {
        "name": "CameraPanSpeed",
        "humanName": "Camera Pan Speed",
        "kind": "number",
        "min": 0,
        "max": 1000,
        "computed": "CameraPanSpeed"
      },
      {
        "name": "NetworkSettings",
        "humanName": "Network Connection",
        "kind": "options",
        "options": [
          {
            "name": "Reliable",
            "apply": {
              "NetworkLossFactor": 0,
              "LinkOutgoingBandwidth": 65536,
              "LinkIncomingSustainedBandwidth": 2048,
              "LinkIncomingPeakBandwidth": 32768,
              "LinkIncomingMaxPacketRate": 64
            }
          },
          {
            "name": "Balanced",
            "apply": {
              "NetworkLossFactor": 1,
              "LinkOutgoingBandwidth": 131072,
              "LinkIncomingSustainedBandwidth": 65536,
              "LinkIncomingPeakBandwidth": 65536,
              "LinkIncomingMaxPacketRate": 512
            }
          },
          {
            "name": "Fast",
            "apply": {
              "NetworkLossFactor": 2,
              "LinkOutgoingBandwidth": 262144,
              "LinkIncomingSustainedBandwidth": 262144,
              "LinkIncomingPeakBandwidth": 262144,
              "LinkIncomingMaxPacketRate": 2048
            }
          }
        ]
      },
      {
        "name": "SmoothBuffer",
        "humanName": "Smooth Buffer",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "apply": {
              "UseNetMessageSmoothingBuffer": 1
            }
          },
          {
            "name": "Off",
            "apply": {
              "UseNetMessageSmoothingBuffer": 0
            }
          }
        ]
      },
      {
        "name": "GcRate",
        "humanName": "GC Rate",
        "kind": "options",
        "options": [
          {
            "name": "Highest performance",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 1.7
            }
          },
          {
            "name": "Higher performance",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 2.4
            }
          },
          {
            "name": "More performance",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 3.2
            }
          },
          {
            "name": "Recommended",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 4.5
            }
          },
          {
            "name": "More Stability",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 6
            }
          },
          {
            "name": "Higher Stability",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 8
            }
          },
          {
            "name": "Highest Stability",
            "apply": {
              "LuaGarbageCollectionMemLoadMult": 10
            }
          }
        ]
      },
      {
        "name": "GcTimeMult",
        "humanName": "GC Time Mult",
        "kind": "options",
        "options": [
          {
            "name": "Highest performance",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 1.4
            }
          },
          {
            "name": "Higher Performance",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 1.7
            }
          },
          {
            "name": "More Performance",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 2
            }
          },
          {
            "name": "Recommended",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 3
            }
          },
          {
            "name": "More Stability",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 4
            }
          },
          {
            "name": "Higher Stability",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 5
            }
          },
          {
            "name": "Highest Stability",
            "apply": {
              "LuaGarbageCollectionRunTimeMult": 6
            }
          }
        ]
      },
      {
        "name": "AtiIntelCompatibility_2",
        "humanName": "ATI/Intel Compatibility",
        "kind": "options",
        "options": [
          {
            "name": "On",
            "computed": "AtiIntelCompatibility_2"
          },
          {
            "name": "Automatic",
            "computed": "AtiIntelCompatibility_2"
          },
          {
            "name": "Off",
            "computed": "AtiIntelCompatibility_2"
          }
        ]
      }
    ]
  }
];

/** What Zero-K ships with, for anything the file on disk does not pin down. */
export const SETTINGS_DEFAULT: Record<string, SettingValue | SettingRef> = {
  "WaterType_2": "Bumpmapped",
  "WaterQuality": "Medium",
  "Shadows": "Units and Terrain",
  "ShadowMapSize": "2048",
  "ShadowDetail": "Medium",
  "ParticleLimit": "15000",
  "TerrainDetail": "Medium",
  "SoftParticles": "Enabled",
  "VegetationDetail": "Medium",
  "FeatureFade": "Off",
  "CompatibilityMode": "Off",
  "AtiIntelCompatibility_2": "Automatic",
  "AntiAliasing": "Low",
  "VSync": "Off",
  "ShaderDetail": "Medium",
  "LupsAirJet": "On",
  "LupsRibbon": "On",
  "LupsNanoParticles": "Cloud",
  "LupsShieldShader": "Default",
  "LupsWaterSettings": "Off",
  "FancySky": "Off",
  "UseNewChili": "Off",
  "InterfaceScale": {
    "ref": "defaultUiScale"
  },
  "MouseZoomSpeed": 25,
  "InvertZoom": "Off",
  "HardwareCursor": "On",
  "TextToSpeech": "On",
  "EdgeScroll": "On",
  "CommandAlpha": 60,
  "QueueIconAlpha": 45,
  "MiddlePanSpeed": 15,
  "CameraPanSpeed": 50,
  "NetworkSettings": "Balanced",
  "SmoothBuffer": "Off",
  "GcRate": "Recommended",
  "GcTimeMult": "Recommended"
};

/** Every setting whose effect upstream expresses as Lua. */
export const COMPUTED: string[] = [
  "AtiIntelCompatibility_2",
  "CameraPanSpeed",
  "CommandAlpha",
  "InterfaceScale",
  "InvertZoom",
  "LupsAirJet",
  "LupsNanoParticles",
  "LupsRibbon",
  "LupsShieldShader",
  "LupsWaterSettings",
  "MiddlePanSpeed",
  "MouseZoomSpeed",
  "QueueIconAlpha",
  "ShaderDetail"
];
