// GENERATED by tools/gen-protocol.mjs - DO NOT EDIT.
// Source: github.com/ZeroK-RTS/Zero-K-Infrastructure @ 48f6f09bc1d0266f204026580671ce867f75d6bd
// Regenerate: node tools/gen-protocol.mjs

import type * as E from "./enums";

export interface Welcome {
  Engine?: string;
  Game?: string;
  UserCount: number;
  Version?: string;
  ChallengeToken?: string;
  ServerPubKey?: string;
  Blacklist?: string[];
  Factions?: Welcome_FactionInfo[];
  UserCountLimited: boolean;
}

export interface Welcome_FactionInfo {
  Name?: string;
  Shortcut?: string;
  Color?: string;
}

export interface NewsList {
  NewsItems?: unknown[];
}

export interface LadderList {
  LadderItems?: unknown[];
}

export interface ForumList {
  ForumItems?: unknown[];
}

export interface DefaultEngineChanged {
  Engine?: string;
}

export interface DefaultGameChanged {
  Game?: string;
}

export interface Login {
  ClientType: E.Login_ClientTypes;
  LobbyVersion?: string;
  Name?: string;
  PasswordHash?: string;
  SteamAuthToken?: string;
  UserID: number;
  InstallID?: string;
  ClientPubKey?: string;
  SignedChallengeToken?: string;
  EncryptedPasswordHash?: string;
  Dlc?: number[];
}

export interface Register {
  Name?: string;
  PasswordHash?: string;
  EncryptedPasswordHash?: string;
  SteamAuthToken?: string;
  Email?: string;
  UserID: number;
  InstallID?: string;
}

export interface RegisterResponse {
  ResultCode: E.RegisterResponse_Code;
  BanReason?: string;
}

export interface LoginResponse {
  Name?: string;
  BanReason?: string;
  ResultCode: E.LoginResponse_Code;
  SessionToken?: string;
}

export interface ChannelHeader {
  ChannelName?: string;
  IsDeluge: boolean;
  Password?: string;
  Topic?: Topic;
  Users?: string[];
}

export interface Topic {
  SetBy?: string;
  SetDate?: string;
  Text?: string;
}

export interface ChangeTopic {
  ChannelName?: string;
  Topic?: Topic;
}

export interface JoinChannel {
  ChannelName?: string;
  Password?: string;
}

export interface LeaveChannel {
  ChannelName?: string;
}

export interface ChannelUserAdded {
  ChannelName?: string;
  UserName?: string;
}

export interface ChannelUserRemoved {
  ChannelName?: string;
  UserName?: string;
}

export interface JoinChannelResponse {
  Channel?: ChannelHeader;
  ChannelName?: string;
  Reason?: string;
  Success: boolean;
}

export interface User {
  AccountID: number;
  Avatar?: string;
  AwaySince?: string;
  BanMute: boolean;
  BanVotes: boolean;
  BanSpecChat: boolean;
  BattleID?: number;
  Clan?: string;
  Country?: string;
  DisplayName?: string;
  Faction?: string;
  InGameSince?: string;
  IsAdmin: boolean;
  IsBot: boolean;
  LobbyVersion?: string;
  Name?: string;
  SteamID?: string;
  Badges?: string[];
  Icon?: string;
  IpAddress?: string;
  PartyID?: number;
  SyncVersion: number;
  RawMmElo: number;
  EffectiveMmElo: number;
  EffectiveElo: number;
  Level: number;
  Rank: number;
}

export interface UserDisconnected {
  Name?: string;
  Reason?: string;
}

export interface Say {
  AllowRelay: boolean;
  IsEmote: boolean;
  Place: E.SayPlace;
  Ring: boolean;
  Target?: string;
  Text?: string;
  Time?: string;
  User?: string;
  Source?: E.SaySource;
}

export interface OpenBattle {
  Header?: BattleHeader;
}

export interface BattleHeader {
  BattleID?: number;
  Engine?: string;
  Founder?: string;
  Game?: string;
  IsMatchMaker?: boolean;
  IsRunning?: boolean;
  Map?: string;
  MaxPlayers?: number;
  Mode?: E.AutohostMode;
  Password?: string;
  PlayerCount?: number;
  RunningSince?: string;
  SpectatorCount?: number;
  Title?: string;
  TimeQueueEnabled?: boolean;
  MaxEvenPlayers?: number;
}

export interface BattleAdded {
  Header?: BattleHeader;
}

export interface BattleUpdate {
  Header?: BattleHeader;
}

export interface BattleRemoved {
  BattleID: number;
}

export interface JoinBattleSuccess {
  BattleID: number;
  Bots?: UpdateBotStatus[];
  Options?: Record<string, string>;
  Players?: UpdateUserBattleStatus[];
  MapOptions?: Record<string, string>;
}

export interface JoinBattle {
  BattleID: number;
  Password?: string;
}

export interface LeaveBattle {
  BattleID?: number;
}

export interface UpdateUserBattleStatus {
  AllyNumber?: number;
  IsSpectator?: boolean;
  QueueOrder?: number;
  Name?: string;
  Sync?: E.SyncStatuses;
  JoinTime?: string;
}

export interface UpdateBotStatus {
  AiLib?: string;
  AllyNumber?: number;
  Name?: string;
  Owner?: string;
}

export interface RemoveBot {
  Name?: string;
}

export interface ChangeUserStatus {
  IsAfk?: boolean;
  IsInGame?: boolean;
}

export interface SetModOptions {
  Options?: Record<string, string>;
}

export interface SetMapOptions {
  Options?: Record<string, string>;
}

export interface KickFromBattle {
  BattleID?: number;
  Name?: string;
  Reason?: string;
}

export interface KickFromServer {
  Name?: string;
  Reason?: string;
}

export interface KickFromChannel {
  ChannelName?: string;
  Reason?: string;
  UserName?: string;
}

export interface ForceJoinChannel {
  ChannelName?: string;
  UserName?: string;
}

export interface ForceJoinBattle {
  BattleID: number;
  Name?: string;
}

export interface SiteToLobbyCommand {
  Command?: string;
}

export interface PwMatchCommand {
  AttackerFactions?: string[];
  Deadline: string;
  DeadlineSeconds: number;
  DefenderFactions?: string[];
  Mode: E.PwMatchCommand_ModeType;
  Options?: PwMatchCommand_VoteOption[];
}

export interface PwMatchCommand_VoteOption {
  Count: number;
  Map?: string;
  Needed: number;
  PlanetID: number;
  PlanetImage?: string;
  StructureImages?: string[];
  IconSize: number;
  PlanetName?: string;
  CanSelectForBattle: boolean;
  PlayerIsAttacker: boolean;
  PlayerIsDefender: boolean;
  AttackerFaction?: string;
  OwnerFaction?: string;
  AttackerAvgWhr: number;
  DefenderAvgWhr?: number;
  WinChance?: number;
}

export interface PwJoinPlanet {
  PlanetID: number;
  AttackerFaction?: string;
}

export interface PwCancel {
  // no members
}

export interface PwRequestJoinPlanet {
  PlanetID: number;
  AttackerFaction?: string;
}

export interface PwJoinPlanetSuccess {
  PlanetID: number;
  AttackerFaction?: string;
}

export interface PwAttackingPlanet {
  PlanetID: number;
  AttackerFaction?: string;
}

export interface JoinFactionRequest {
  Faction?: string;
}

export interface PwStatus {
  PlanetWarsMode?: unknown;
  PlanetWarsNextMode?: unknown;
  PlanetWarsNextModeTime?: string;
  MinLevel: number;
  AttackerPhaseMinutes: number;
  DefenderPhaseMinutes: number;
  MaxAttackCharges: number;
}

export interface PwAttackCharges {
  Current: number;
  NextRechargeTime?: string;
}

export interface SetAccountRelation {
  Relation: E.Relation;
  SteamID?: string;
  TargetName?: string;
}

export interface ConnectSpring {
  Engine?: string;
  Game?: string;
  Ip?: string;
  Map?: string;
  Port: number;
  ScriptPassword?: string;
  Mode: E.AutohostMode;
  Title?: string;
  IsSpectator: boolean;
}

export interface RejoinOption {
  BattleID: number;
}

export interface RequestConnectSpring {
  BattleID: number;
  Password?: string;
}

export interface FriendList {
  Friends?: FriendEntry[];
}

export interface FriendEntry {
  Name?: string;
  SteamID?: string;
}

export interface IgnoreList {
  Ignores?: string[];
}

export interface BattleDebriefing {
  DebriefingUsers?: Record<string, BattleDebriefing_DebriefingUser>;
  ChatChannel?: string;
  Message?: string;
  ServerBattleID: number;
  Url?: string;
  RatingCategory?: string;
}

export interface BattleDebriefing_DebriefingAward {
  Description?: string;
  Key?: string;
  Value?: number;
}

export interface BattleDebriefing_DebriefingUser {
  AllyNumber: number;
  Awards?: unknown;
  EloChange: number;
  IsInVictoryTeam: boolean;
  IsLevelUp: boolean;
  IsRankup: boolean;
  IsRankdown: boolean;
  NewElo: number;
  NextRankElo: number;
  PrevRankElo: number;
  NewRank: number;
  LoseTime: number;
  XpChange: number;
  NewXp: number;
  NextLevelXp: number;
  PrevLevelXp: number;
  AccountID: number;
}

export interface UserProfile {
  Name?: string;
  Awards?: UserProfile_UserAward[];
  Badges?: string[];
  Level: number;
  LevelUpRatio?: string;
  Rank: number;
  RankUpRatio?: string;
  EffectiveElo: number;
  EffectiveMmElo: number;
  EffectivePwElo: number;
  Kudos: number;
  PwMetal?: string;
  PwDropships?: string;
  PwBombers?: string;
  PwWarpcores?: string;
}

export interface UserProfile_UserAward {
  AwardKey?: string;
  Collected: number;
}

export interface BattlePoll {
  Topic?: string;
  Url?: string;
  Options?: BattlePoll_PollOption[];
  VotesToWin: number;
  YesNoVote: boolean;
  MapSelection: boolean;
  NotifyPoll: boolean;
  MapName?: string;
}

export interface BattlePoll_PollOption {
  Name?: string;
  DisplayName?: string;
  Id: number;
  Votes: number;
  Url?: string;
}

export interface BattlePollOutcome {
  WinningOption?: BattlePoll_PollOption;
  Topic?: string;
  Message?: string;
  Success: boolean;
  YesNoVote: boolean;
  MapSelection: boolean;
}

export interface UserReport {
  Username?: string;
  Text?: string;
}

export interface GetCustomGameMode {
  ShortName?: string;
}

export interface CustomGameModeResponse {
  ShortName?: string;
  DisplayName?: string;
  GameModeJson?: string;
}

export interface MatchMakerSetup {
  PossibleQueues?: MatchMakerSetup_Queue[];
}

export interface MatchMakerSetup_Queue {
  Name?: string;
  Description?: string;
  Maps?: string[];
  Game?: string;
  MaxPartySize: number;
  UseWinChanceLimit: boolean;
  UseCasualElo: boolean;
  MinWinChanceMult: number;
  MinWinChanceOffset: number;
  UseHandicap: boolean;
  MaxSize: number;
  MinSize: number;
  EloCutOffExponent: number;
  Mode: E.AutohostMode;
  SafeMaps?: string[];
}

export interface MatchMakerQueueRequest {
  Queues?: string[];
}

export interface MatchMakerStatus {
  JoinedQueues?: string[];
  QueueCounts?: Record<string, number>;
  CurrentEloWidth?: number;
  JoinedTime?: string;
  BannedSeconds?: number;
  InstantStartQueues?: string[];
  IngameCounts?: Record<string, number>;
  UserCount: number;
  UserCountDiscord: number;
}

export interface AreYouReady {
  MinimumWinChance: number;
  QuickPlay: boolean;
  SecondsRemaining: number;
}

export interface AreYouReadyUpdate {
  ReadyAccepted: boolean;
  LikelyToPlay: boolean;
  QueueReadyCounts?: Record<string, number>;
  YourBattleSize?: number;
  YourBattleReady?: number;
}

export interface AreYouReadyResult {
  IsBattleStarting: boolean;
  AreYouBanned: boolean;
}

export interface AreYouReadyResponse {
  Ready: boolean;
}

export interface InviteToParty {
  UserName?: string;
}

export interface LeaveParty {
  PartyID: number;
}

export interface PartyInviteResponse {
  PartyID: number;
  Accepted: boolean;
}

export interface OnPartyInvite {
  PartyID: number;
  UserNames?: string[];
  TimeoutSeconds: number;
}

export interface OnPartyStatus {
  PartyID: number;
  UserNames?: string[];
}

export interface UserBattleStatus {
  AllyNumber: number;
  IsSpectator: boolean;
  QueueOrder: number;
  JoinTime: string;
  Name?: string;
  ScriptPassword?: string;
  SyncStatus: E.SyncStatuses;
  LobbyUser?: User;
}

