#!/usr/bin/env node
/**
 * Regenerates src/ds/icons.js - the set of lucide icons this app draws.
 *
 * The design bundle reaches for `lucide.icons[name]`, which pulls all 1743 of
 * them into the build: most of a megabyte for the thirty-odd we use. Naming
 * them explicitly lets the bundler drop the rest.
 *
 *   node tools/gen-icons.mjs        # rewrite the list
 *   node tools/gen-icons.mjs --check   # fail if it is out of date
 *
 * Icon names are read out of the source, so adding `icon="rocket"` to a screen
 * and re-running is all it takes. Deep import paths come from lucide's own
 * alias barrel, because several names the design kit uses are aliases:
 * `alert-triangle` lives in `triangle-alert.js`.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "ds", "icons.js");
const ALIASES = join(ROOT, "node_modules", "lucide", "dist", "esm", "iconsAndAliases.js");

const pascal = n => n.split(/[-_\s]+/).filter(Boolean)
  .map(w => w[0].toUpperCase() + w.slice(1)).join("");

/** Every `icon="..."`, `iconRight="..."` and `name: "..."` in the source. */
function usedNames() {
  const names = new Set();
  const walk = dir => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if ([".js", ".jsx", ".ts", ".tsx"].includes(extname(entry.name))) {
        const text = readFileSync(path, "utf8");
        for (const m of text.matchAll(/(?:icon|iconRight|name)\s*[:=]\s*"([a-z0-9-]+)"/g)) {
          names.add(m[1]);
        }
      }
    }
  };
  walk(join(ROOT, "src"));
  return names;
}

/** Exported name -> module path, aliases included. */
function iconModules() {
  const map = new Map();
  const barrel = readFileSync(ALIASES, "utf8");
  for (const m of barrel.matchAll(/export \{([^}]+)\} from '(\.\/icons\/[^']+)';/g)) {
    const path = m[2].replace("./", "lucide/dist/esm/");
    for (const part of m[1].split(",")) {
      const as = part.trim().match(/default as (\w+)/);
      if (as) map.set(as[1], path);
    }
  }
  return map;
}

const modules = iconModules();
const used = [...usedNames()].filter(n => modules.has(pascal(n))).sort();
const unknown = [...usedNames()].filter(n => !modules.has(pascal(n)));

const header = `/* The icons this app draws. GENERATED by tools/gen-icons.mjs - do not hand-edit.
 *
 * The design bundle reaches for \`lucide.icons[name]\`, which pulls all 1743 of
 * them into the build. Naming the ones we use lets the bundler drop the rest.
 * Several are aliases - \`alert-triangle\` really lives in \`triangle-alert.js\` -
 * which is why the paths come from lucide's own barrel rather than from the name.
 *
 * Add an icon to a screen, then re-run the generator; \`npm run check:icons\`
 * fails the build review if this file has drifted.
 */
`;

const body = header
  + used.map(n => `import ${pascal(n)} from "${modules.get(pascal(n))}";`).join("\n")
  + "\n\nexport const ICONS = {\n"
  + used.map(n => `  "${n}": ${pascal(n)},`).join("\n")
  + "\n};\n";

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing counts as stale */ }
  // Compare content, not bytes. Git may have checked this file out with CRLF
  // (core.autocrlf is on by default on Windows, including the CI runner) while
  // the generator always writes LF, and a raw !== then fails for a file that is
  // perfectly up to date. .gitattributes pins eol=lf too; this is the belt to
  // that braces, because it holds whatever a contributor's git config says.
  const normalize = s => s.replace(/\r\n/g, "\n");
  if (normalize(current) !== normalize(body)) {
    console.error("src/ds/icons.js is out of date - run: node tools/gen-icons.mjs");
    process.exit(1);
  }
  console.log(`icons up to date (${used.length})`);
} else {
  writeFileSync(OUT, body);
  console.log(`${used.length} icons`);
}

// Names that are not lucide icons are almost always a false positive from the
// `name: "..."` pattern (a player called `hexed`), so this is a note, not a failure.
if (unknown.length) console.log(`ignored non-icon names: ${unknown.join(", ")}`);
