/* The icons this app draws. GENERATED by tools/gen-icons.mjs - do not hand-edit.
 *
 * The design bundle reaches for `lucide.icons[name]`, which pulls all 1743 of
 * them into the build. Naming the ones we use lets the bundler drop the rest.
 * Several are aliases - `alert-triangle` really lives in `triangle-alert.js` -
 * which is why the paths come from lucide's own barrel rather than from the name.
 *
 * Add an icon to a screen, then re-run the generator; `npm run check:icons`
 * fails the build review if this file has drifted.
 */
import AlertTriangle from "lucide/dist/esm/icons/triangle-alert.js";
import ArrowDown from "lucide/dist/esm/icons/arrow-down.js";
import ArrowLeft from "lucide/dist/esm/icons/arrow-left.js";
import Check from "lucide/dist/esm/icons/check.js";
import ChevronDown from "lucide/dist/esm/icons/chevron-down.js";
import ChevronUp from "lucide/dist/esm/icons/chevron-up.js";
import Cpu from "lucide/dist/esm/icons/cpu.js";
import Crown from "lucide/dist/esm/icons/crown.js";
import Download from "lucide/dist/esm/icons/download.js";
import ExternalLink from "lucide/dist/esm/icons/external-link.js";
import Eye from "lucide/dist/esm/icons/eye.js";
import Info from "lucide/dist/esm/icons/info.js";
import Loader from "lucide/dist/esm/icons/loader.js";
import Lock from "lucide/dist/esm/icons/lock.js";
import LogOut from "lucide/dist/esm/icons/log-out.js";
import MessageSquare from "lucide/dist/esm/icons/message-square.js";
import Minus from "lucide/dist/esm/icons/minus.js";
import Play from "lucide/dist/esm/icons/play.js";
import Plus from "lucide/dist/esm/icons/plus.js";
import RotateCcw from "lucide/dist/esm/icons/rotate-ccw.js";
import Search from "lucide/dist/esm/icons/search.js";
import Settings from "lucide/dist/esm/icons/settings.js";
import Shield from "lucide/dist/esm/icons/shield.js";
import Square from "lucide/dist/esm/icons/square.js";
import Swords from "lucide/dist/esm/icons/swords.js";
import Target from "lucide/dist/esm/icons/target.js";
import Trophy from "lucide/dist/esm/icons/trophy.js";
import User from "lucide/dist/esm/icons/user.js";
import Users from "lucide/dist/esm/icons/users.js";
import Wifi from "lucide/dist/esm/icons/wifi.js";
import WifiOff from "lucide/dist/esm/icons/wifi-off.js";
import X from "lucide/dist/esm/icons/x.js";

export const ICONS = {
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "cpu": Cpu,
  "crown": Crown,
  "download": Download,
  "external-link": ExternalLink,
  "eye": Eye,
  "info": Info,
  "loader": Loader,
  "lock": Lock,
  "log-out": LogOut,
  "message-square": MessageSquare,
  "minus": Minus,
  "play": Play,
  "plus": Plus,
  "rotate-ccw": RotateCcw,
  "search": Search,
  "settings": Settings,
  "shield": Shield,
  "square": Square,
  "swords": Swords,
  "target": Target,
  "trophy": Trophy,
  "user": User,
  "users": Users,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "x": X,
};
